# Generated by Django 3.0.7 on 2020-06-16 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbv_demo', '0002_auto_20200616_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venue',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='venue',
            table='t_venues',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('record_status', models.PositiveIntegerField()),
                ('version', models.BigIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=250)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_teams',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('record_status', models.PositiveIntegerField()),
                ('version', models.BigIntegerField()),
                ('name_in_full', models.CharField(max_length=150)),
                ('title', models.CharField(choices=[('MR.', 'MR.'), ('MRS.', 'MRS.'), ('MS.', 'MS.')], default='MR.', max_length=4)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('age', models.SmallIntegerField()),
                ('initials', models.CharField(max_length=50)),
                ('calling_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('email', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('player_position', models.CharField(choices=[('CEN', 'Centre'), ('PWF', 'Power Forward'), ('SMF', 'Small Forward'), ('SHG', 'Shooting Guard'), ('POG', 'Point Guard')], default='CEN', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_players',
            },
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('record_status', models.PositiveIntegerField()),
                ('version', models.BigIntegerField()),
                ('name_in_full', models.CharField(max_length=150)),
                ('title', models.CharField(choices=[('MR.', 'MR.'), ('MRS.', 'MRS.'), ('MS.', 'MS.')], default='MR.', max_length=4)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('age', models.SmallIntegerField()),
                ('initials', models.CharField(max_length=50)),
                ('calling_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('email', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('official_type', models.CharField(choices=[('REF', 'Referee'), ('GAM', 'Game Manager'), ('GRS', 'Ground Staff')], default='REF', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_officials',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('record_status', models.PositiveIntegerField()),
                ('version', models.BigIntegerField()),
                ('name_in_full', models.CharField(max_length=150)),
                ('title', models.CharField(choices=[('MR.', 'MR.'), ('MRS.', 'MRS.'), ('MS.', 'MS.')], default='MR.', max_length=4)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('age', models.SmallIntegerField()),
                ('initials', models.CharField(max_length=50)),
                ('calling_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('email', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=50)),
                ('position_type', models.CharField(choices=[('CO', 'Coach'), ('MA', 'Manager'), ('AM', 'Assistant Manager')], default='CO', max_length=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_team_management',
            },
        ),
    ]
